powercap: intel_rapl: Add support for RAPTORLAKE and RAPTORLAKE_P
projectceladon/linux-intel-lts2021 pull request #8
Opened 2023-07-19 06:57 UTC by cyxlily

Add RAPTORLAKE and RAPTORLAKE_P to the list of
supported processor models in the Intel RAPL
power capping driver.

Tracked-On: OAM-111246

2023-07-20 03:47 UTC, qizhangz commented
@JeevakaPrabu Could you please review this PR? The change shoud be ported from upstream.

2023-07-20 04:31 UTC, JeevakaPrabu requested changes
powercap: intel_rapl: Add support for RAPTORLAKE and RAPTORLAKE_P

Add RAPTORLAKE and RAPTORLAKE_P to the list of supported processor
models in the Intel RAPL power capping driver.

Tracked-On: OAM-111246
Signed-off-by: Cui, Yuxin <yuxin.cui@intel.com>

2023-07-25 02:40 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/361

2023-08-02 01:19 UTC, cyxlily commented
Merged with https://github.com/projectceladon/linux-intel-lts2021/commit/a4679f9653eaef096dc6c9235dae3c970b338508

2023-08-02 01:51 UTC, closed without merging